spring:
  application:
    name: mp-checkout-pro

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pm_api}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mercadopago:
    access-token: ${MP_ACESS_TOKEN}
    notification-url: ${MP_NOTIFICATION_URL:http://localhost:${server.port}/api/payments/webhook}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
